// Bundle only an explicit public documentation allowlist. The runtime never
// turns a resource URI into a filesystem path or reads the caller's files.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, relative, resolve, posix } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

export const WIKI_SOURCES = Object.freeze({
  index: 'docs/wiki/README.md',
  status: 'docs/wiki/status.md',
  architecture: 'docs/wiki/architecture.md',
  protocol: 'docs/wiki/protocol.md',
  workflows: 'docs/wiki/workflows.md',
  mcp: 'docs/wiki/mcp.md',
  domain: 'docs/wiki/domain.md',
  'repo-guide': 'docs/wiki/repo-guide.md',
  'tool-index': 'docs/MCP_TOOL_INDEX.md',
});
const defaultRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const uriFor = (key) => key === 'index' ? 'takeoff://wiki' : `takeoff://wiki/${key}`;

export function wikiBundle(root = defaultRoot) {
  const actual = readdirSync(resolve(root, 'docs/wiki')).filter(p => p.endsWith('.md')).map(p => `docs/wiki/${p}`).sort();
  const expected = Object.values(WIKI_SOURCES).filter(p => p.startsWith('docs/wiki/')).sort();
  if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error('Wiki source pages and the explicit resource allowlist differ; add or remove their mapping together.');
  const version = JSON.parse(readFileSync(resolve(root, 'mcp/package.json'), 'utf8')).version;
  const keysBySource = new Map(Object.entries(WIKI_SOURCES).map(([key, source]) => [source, key]));
  const pages = Object.entries(WIKI_SOURCES).map(([key, source]) => {
    // Canonical LF text gives identical hashes on Windows and POSIX checkouts.
    const original = readFileSync(resolve(root, source), 'utf8').replace(/\r\n/g, '\n');
    const title = original.match(/^# (.+)$/m)?.[1];
    if (!title) throw new Error(`${source} needs a title`);
    // Wiki-to-wiki navigation stays within resources. Code/reference links
    // browse the repository; no local path from the caller is ever opened.
    const text = original.replace(/\]\(([^)]+)\)/g, (whole, href) => {
      if (/^(?:[a-z][a-z0-9+.-]*:|#)/i.test(href)) return whole;
      const [path, fragment] = href.split('#');
      const target = posix.normalize(posix.join(posix.dirname(source), path));
      if (target.startsWith('../')) throw new Error(`${source}: link escapes the repository: ${href}`);
      const wikiKey = keysBySource.get(target);
      const link = wikiKey ? uriFor(wikiKey) : `https://github.com/Kentucky-ai/opentakeoff/blob/main/${target}`;
      // Resources address complete pages; section headings remain in the page.
      return `](${link}${!wikiKey && fragment ? `#${fragment}` : ''})`;
    });
    return { key, uri: uriFor(key), title, source, source_sha256: createHash('sha256').update(original).digest('hex'), text };
  });
  return { version, pages };
}

export function renderWiki(root = defaultRoot) {
  const bundle = wikiBundle(root);
  return '// Generated by scripts/check-wiki.mjs from public documentation. Do not edit.\n'
    + '// Resource links read packaged pages; repository source links browse main.\n'
    + `export const WIKI_VERSION = ${JSON.stringify(bundle.version)};\n`
    + `export const WIKI_PAGES = ${JSON.stringify(bundle.pages, null, 2)} as const;\n`;
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const target = resolve(defaultRoot, 'mcp/src/wiki.generated.ts');
  const generated = renderWiki();
  let old = '';
  try { old = readFileSync(target, 'utf8').replace(/\r\n/g, '\n'); } catch (e) { if (e.code !== 'ENOENT') throw e; }
  if (old !== generated) {
    if (process.argv.includes('--write')) writeFileSync(target, generated);
    else { console.error(`${relative(defaultRoot, target)} is stale — run npm run check:wiki -- --write`); process.exitCode = 1; }
  }
  console.log(`Wiki bundle: ${Object.keys(WIKI_SOURCES).length} public pages; version and content checked against source.`);
}
